export const projects = [
  {
    title: "Network Vulnerability Scanner",
    description: "A comprehensive tool for identifying and assessing network vulnerabilities",
    category: "Security Tools",
    tags: ["Python", "Nmap", "Network Security", "Vulnerability Assessment"],
    image: "/placeholder.svg?height=192&width=384",
    githubUrl: "https://github.com",
    demoUrl: "#",
    slug: "network-scanner",
  },
  {
    title: "Web Application Firewall",
    description: "Custom WAF implementation to protect web applications from common attacks",
    category: "Web Security",
    tags: ["Node.js", "Express", "WAF", "Security Rules"],
    image: "/placeholder.svg?height=192&width=384",
    githubUrl: "https://github.com",
    demoUrl: "#",
    slug: "web-application-firewall",
  },
  {
    title: "Phishing Detection System",
    description: "ML-powered system to detect and alert users about potential phishing attempts",
    category: "Security Tools",
    tags: ["Python", "Machine Learning", "Anti-Phishing", "TensorFlow"],
    image: "/placeholder.svg?height=192&width=384",
    githubUrl: "https://github.com",
    slug: "phishing-detection",
  },
  {
    title: "Secure Coding Practices Guide",
    description: "Comprehensive guide for developers on implementing secure coding practices",
    category: "Research",
    tags: ["Secure Coding", "OWASP", "Best Practices", "Documentation"],
    image: "/placeholder.svg?height=192&width=384",
    githubUrl: "https://github.com",
    demoUrl: "#",
    slug: "secure-coding-guide",
  },
  {
    title: "IoT Security Framework",
    description: "Security framework for Internet of Things devices and networks",
    category: "Research",
    tags: ["IoT", "Security Framework", "Embedded Systems", "Network Security"],
    image: "/placeholder.svg?height=192&width=384",
    githubUrl: "https://github.com",
    slug: "iot-security-framework",
  },
  {
    title: "Password Strength Analyzer",
    description: "Tool to analyze and improve password security with recommendations",
    category: "Security Tools",
    tags: ["JavaScript", "Cryptography", "Password Security"],
    image: "/placeholder.svg?height=192&width=384",
    githubUrl: "https://github.com",
    demoUrl: "#",
    slug: "password-analyzer",
  },
  {
    title: "Penetration Testing Framework",
    description: "Modular framework for conducting comprehensive penetration tests",
    category: "Penetration Testing",
    tags: ["Python", "Penetration Testing", "Security Assessment", "Exploitation"],
    image: "/placeholder.svg?height=192&width=384",
    githubUrl: "https://github.com",
    slug: "pentest-framework",
  },
  {
    title: "Security Headers Analyzer",
    description: "Tool to analyze and recommend HTTP security headers for web applications",
    category: "Web Security",
    tags: ["JavaScript", "HTTP Headers", "Web Security"],
    image: "/placeholder.svg?height=192&width=384",
    githubUrl: "https://github.com",
    demoUrl: "#",
    slug: "security-headers",
  },
  {
    title: "Malware Analysis Toolkit",
    description: "Collection of tools for analyzing and understanding malware behavior",
    category: "Security Tools",
    tags: ["Python", "Malware Analysis", "Reverse Engineering", "Sandbox"],
    image: "/placeholder.svg?height=192&width=384",
    githubUrl: "https://github.com",
    slug: "malware-toolkit",
  },
]

